In [1]:
import pandas as pd

In [2]:
#load dataset and preprocess
twt = pd.read_csv('train.csv')
twt = twt.set_index('id')

In [3]:
print(twt.info())
twt.loc[~twt['keyword'].isna()]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7613 entries, 1 to 10873
Data columns (total 4 columns):
keyword     7552 non-null object
location    5080 non-null object
text        7613 non-null object
target      7613 non-null int64
dtypes: int64(1), object(3)
memory usage: 297.4+ KB
None

,keyword,location,text,target
id,,,,
48,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
49,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0
50,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
52,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0
53,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
54,ablaze,Pretoria,@PhDSquares #mufc they've built so much hype a...,0
55,ablaze,World Wide!!,INEC Office in Abia Set Ablaze - http://t.co/3...,1
56,ablaze,NaN,Barbados #Bridgetown JAMAICA ÛÒ Two cars set ...,1
57,ablaze,Paranaque City,Ablaze for you Lord :D,0
59,ablaze,Live On Webcam,Check these out: http://t.co/rOI2NSmEJJ http:/...,0
61,ablaze,NaN,on the outside you're ablaze and alive\nbut yo...,0
62,ablaze,milky way,Had an awesome time visiting the CFC head offi...,0
63,ablaze,NaN,SOOOO PUMPED FOR ABLAZE ???? @southridgelife,0
64,ablaze,NaN,I wanted to set Chicago ablaze with my preachi...,0
65,ablaze,NaN,I gained 3 followers in the last week. You? Kn...,0
66,ablaze,"GREENSBORO,NORTH CAROLINA",How the West was burned: Thousands of wildfire...,1
67,ablaze,NaN,Building the perfect tracklist to life leave t...,0
68,ablaze,Live On Webcam,Check these out: http://t.co/rOI2NSmEJJ http:/...,0
71,ablaze,England.,First night with retainers in. It's quite weir...,0
73,ablaze,"Sheffield Township, Ohio",Deputies: Man shot before Brighton home set ab...,1
74,ablaze,India,Man wife get six years jail for setting ablaze...,1
76,ablaze,Barbados,SANTA CRUZ ÛÓ Head of the St Elizabeth Police...,0
77,ablaze,Anaheim,Police: Arsonist Deliberately Set Black Church...,1
78,ablaze,Abuja,Noches El-Bestia '@Alexis_Sanchez: happy to se...,0
79,ablaze,USA,#Kurds trampling on Turkmen flag later set it ...,1
80,ablaze,South Africa,TRUCK ABLAZE : R21. VOORTREKKER AVE. OUTSIDE O...,1
81,ablaze,"Sao Paulo, Brazil",Set our hearts ablaze and every city was a gif...,0
82,ablaze,hollywoodland,They sky was ablaze tonight in Los Angeles. I'...,0
83,ablaze,"Edmonton, Alberta - Treaty 6",How the West was burned: Thousands of wildfire...,1
85,ablaze,NaN,Revel in yours wmv videos by means of mac fare...,0
...,...,...,...,...
10798,wrecked,NaN,#news Cramer: Iger's 3 words that wrecked Disn...,0
10799,wrecked,NaN,James Kunstler: How bad architecture wrecked c...,0
10800,wrecked,Milwaukee County,http://t.co/DeQQOpSP4f: Iger's 3 words that wr...,0
10802,wrecked,"Click the link below, okay",The Twitter update pretty much wrecked the app,0
10803,wrecked,NaN,You wrecked me. Never felt so low in my life. ...,0
10805,wrecked,probably not home,coleslaw #wrecked http://t.co/sijNBmCZIJ,0
10808,wrecked,NaN,300K exotic car wrecked in train accident \nht...,1
10809,wrecked,NaN,The twins pitcher's ego is now WRECKED,0
10810,wrecked,6,@Tunes_WGG lol. U got wrecked,0
10811,wrecked,NaN,you wrecked my whole world,0
10812,wrecked,NaN,I wrecked my stomach help,0
10813,wrecked,NaN,@__ohhmyjoshh @stevenrulles he not gonna be th...,0
10814,wrecked,NaN,Wrecked tired but not gonna be asleep before 3??,0
10815,wrecked,United States,http://t.co/qVx0VQTPz0 Cramer: Iger's 3 words ...,0
10817,wrecked,At your back,Wrecked emotions.,0
10818,wrecked,NaN,The Riddler would be the best early-exit prima...,0
10819,wrecked,"Livingston, MT",@marynmck That's beyond adorable. I hope it wo...,0
10821,wrecked,California,Cramer: Iger's 3 words that wrecked Disney's s...,0
10822,wrecked,Glasgow,@Caitsroberts see U the night wee bArra to get...,0
10823,wrecked,"Manhattan, NY",@Kirafrog @mount_wario Did you get wrecked again?,1
10824,wrecked,"Denton, Texas",Had an awesome time gettin wrecked at bowling ...,0
10825,wrecked,Global,Cramer: 3 words that wrecked DIS stock - http:...,0
10826,wrecked,TN,On the bright side I wrecked http://t.co/uEa0t...,0
10827,wrecked,NaN,He just wrecked all of you http://t.co/y46isyZkC8,0
10829,wrecked,#NewcastleuponTyne #UK,@widda16 ... He's gone. You can relax. I thoug...,0
10830,wrecked,NaN,@jt_ruff23 @cameronhacker and I wrecked you both,0
10831,wrecked,"Vancouver, Canada",Three days off from work and they've pretty mu...,0
10832,wrecked,London,#FX #forex #trading Cramer: Iger's 3 words tha...,0
10833,wrecked,Lincoln,@engineshed Great atmosphere at the British Li...,0
10834,wrecked,NaN,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [4]:
twt['target'].mean()

0.4296597924602653

In [5]:
import torch
from transformers import GPT2Tokenizer, pipeline
import numpy as np

//anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
//anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
//anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
//anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
//anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
//anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
//anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
//anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
//anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
//anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
//anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
//anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [11]:
extract_features = pipeline('feature-extraction',tokenizer='GPT2Tokenizer')

HBox(children=(IntProgress(value=0, description='Downloading', max=230, style=ProgressStyle(description_width=…

In [12]:
np.array(extract_features('hello there')).flatten().shape

(3072,)

In [13]:
twt['text'].shape

(7613,)

In [14]:
np.array(extract_features(['Just spend 5 minutes ','thinking','of the people whos love made you'])).shape

(3, 10, 768)

In [24]:
# different number of embedding layers per extraction, can experiment with averaging all, taking last layer, etc.
print(np.array(extract_features(twt['text'].iloc[0])).shape)
print(np.array(extract_features(twt['text'].iloc[1])).shape)

(1, 16, 768)
(1, 12, 768)